In [0]:
from google.colab import auth
auth.authenticate_user()

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive

In [0]:
import pandas as pd
import numpy as np
from functools import reduce

import sys
sys.path.insert(0, './gdrive/My Drive/Colab Notebooks/')

import functions as f # sample function from RECSYS2019

In [0]:
path = './gdrive/My Drive/data/'
test = path + 'test.csv'

df_test = pd.read_csv(test)

# FUNCTION GOAL(interactions): 
## 마지막 clickout item에 해당하는 row들의 reference만 고려해 counts 순위로 ranking정하기

## CASE 1 
clickout 개수가 1개인 session 
* df_mono: 한 session내에서 clickout 횟수가 1번인 session들의 df
* df_target: df_mono의 target row

In [0]:
def mono(df):
  s = (df.loc[df.action_type == 'clickout item'].groupby('session_id').action_type.count() == 1)
  mono_sess_index = s.index[s].to_list() # return session_id index
  df_mono = df.loc[df.session_id.isin(mono_sess_index)]
  
  return df_mono

In [0]:
df_mono = mono(df_test)

In [0]:
df_mono

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
7,009RGHI3G9A3,f05ab0de907e2,1541570935,1,interaction item info,7065316,IN,"Nathdwara, India",mobile,NaN,NaN,NaN
8,009RGHI3G9A3,f05ab0de907e2,1541570940,2,clickout item,NaN,IN,"Nathdwara, India",mobile,NaN,10884872|7065316,64|28
62,0339C84S24ET,3e7d55eae386f,1541622138,1,interaction item image,8511456,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
63,0339C84S24ET,3e7d55eae386f,1541622138,2,interaction item image,8511456,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
64,0339C84S24ET,3e7d55eae386f,1541622146,3,clickout item,8511456,TR,"Antalya, Turkey",mobile,NaN,10598152|7031496|7348404|5753730|7238840|69382...,16|58|22|50|28|39|22|158|43|30|17|76|22
65,0339C84S24ET,3e7d55eae386f,1541622335,4,search for poi,Antalya Expo Center,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
66,0339C84S24ET,3e7d55eae386f,1541622358,5,search for poi,Antalya Expo Center,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
67,0339C84S24ET,3e7d55eae386f,1541622381,6,interaction item image,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
68,0339C84S24ET,3e7d55eae386f,1541622381,7,interaction item image,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
69,0339C84S24ET,3e7d55eae386f,1541622391,8,interaction item info,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
70,0339C84S24ET,3e7d55eae386f,1541622515,9,interaction item image,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
71,0339C84S24ET,3e7d55eae386f,1541622515,10,interaction item image,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
72,0339C84S24ET,3e7d55eae386f,1541622525,11,interaction item rating,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
73,0339C84S24ET,3e7d55eae386f,1541622545,12,interaction item deals,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
74,0339C84S24ET,89171d441a304,1541615122,1,interaction item info,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
75,0339C84S24ET,89171d441a304,1541615132,2,interaction item rating,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
76,0339C84S24ET,89171d441a304,1541615142,3,interaction item deals,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
77,0339C84S24ET,89171d441a304,1541615193,4,interaction item image,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
78,0339C84S24ET,89171d441a304,1541615193,5,interaction item image,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
79,0339C84S24ET,89171d441a304,1541615201,6,interaction item image,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
80,0339C84S24ET,89171d441a304,1541615551,7,interaction item image,8160620,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
81,0339C84S24ET,89171d441a304,1541615551,8,interaction item image,8160620,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
82,0339C84S24ET,89171d441a304,1541615580,9,interaction item image,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
83,0339C84S24ET,89171d441a304,1541615655,10,interaction item image,37717,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
84,0339C84S24ET,89171d441a304,1541615655,11,interaction item image,37717,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
85,0339C84S24ET,89171d441a304,1541615665,12,interaction item image,37717,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
86,0339C84S24ET,89171d441a304,1541615665,13,interaction item image,37717,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
87,0339C84S24ET,89171d441a304,1541615665,14,interaction item image,37717,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
88,0339C84S24ET,89171d441a304,1541615665,15,interaction item image,37717,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
89,0339C84S24ET,89171d441a304,1541615665,16,interaction item image,37717,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3781824,ZVTSO44R1US2,ba077694ccf39,1541673393,34,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN
3781825,ZVTSO44R1US2,ba077694ccf39,1541673403,35,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN
3781826,ZVTSO44R1US2,ba077694ccf39,1541673403,36,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN
3781827,ZVTSO44R1US2,ba077694ccf39,1541673403,37,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN
3781828,ZVTSO44R1US2,ba077694ccf39,1541673403,38,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN
3781829,ZVTSO44R1US2,ba077694ccf39,1541673403,39,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN
3781830,ZVTSO44R1US2,ba077694ccf39,1541673403,40,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN
3781831,ZVTSO44R1US2,ba077694ccf39,1541673403,41,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN
3781832,ZVTSO44R1US2,ba077694ccf39,1541673403,42,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN
3781833,ZVTSO44R1US2,ba077694ccf39,1541673403,43,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN
3781834,ZVTSO44R1US2,ba077694ccf39,1541673403,44,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN
3781835,ZVTSO44R1US2,ba077694ccf39,1541673403,45,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN
3781836,ZVTSO44R1US2,ba077694ccf39,1541673403,46,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN
3781837,ZVTSO44R1US2,ba077694ccf39,1541673403,47,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN
3781838,ZVTSO44R1US2,ba077694ccf39,1541673403,48,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN
3781839,ZVTSO44R1US2,ba077694ccf39,1541673409,49,clickout item,NaN,JP,"Sapporo, Japan",desktop,Hotel|Resort|Best Value|Hammam,5863172|494271|1042070|103453|9327438|2111024|...,72|90|100|92|81|86|92|83|81|100|105|104|95|87|...
3781840,ZVUSADAHBEMO,f5f4f9aa82b44,1541678661,1,clickout item,NaN,DE,"Grainau, Germany",desktop,NaN,51656|96015|52072|5465|5470|5484|117981|255274...,146|200|124|99|88|133|112|85|79|95|87|95|95|91...
3781845,ZWD4F2A7H5EK,3e4fdd55f6145,1541670674,1,interaction item info,20259,IT,"Milan, Italy",desktop,NaN,NaN,NaN
3781846,ZWD4F2A7H5EK,3e4fdd55f6145,1541670697,2,clickout item,NaN,IT,"Milan, Italy",desktop,NaN,20259|20339|20363|20400|20407|954207|20564|202...,77|73|77|66|84|22|86|76|77|78|81|74|94|84|74|7...
3782318,ZXGCLNDBW84E,53cb30d7ca9c6,1541702970,1,search for destination,"Fortaleza, Brazil",BR,"Fortaleza, Brazil",desktop,NaN,NaN,NaN
3782319,ZXGCLNDBW84E,53cb30d7ca9c6,1541703012,2,search for destination,"Porto Seguro, Brazil",BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782320,ZXGCLNDBW84E,53cb30d7ca9c6,1541703034,3,search for item,477936,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782321,ZXGCLNDBW84E,53cb30d7ca9c6,1541703038,4,clickout item,477936,BR,"Porto Seguro, Brazil",desktop,NaN,477936|1326068|1668443|503361|1886269|478656|5...,42|49|36|170|40|45|38|140|60|57|75|53|153|71|6...
3782322,ZYG4MMKT847V,0f128fd98b4e3,1541634316,1,search for destination,"Resende, Brazil",BR,"Resende, Brazil",mobile,NaN,NaN,NaN
3782323,ZYG4MMKT847V,0f128fd98b4e3,1541634383,2,interaction item image,1089752,BR,"Resende, Brazil",mobile,NaN,NaN,NaN
3782324,ZYG4MMKT847V,0f128fd98b4e3,1541634383,3,interaction item image,1089752,BR,"Resende, Brazil",mobile,NaN,NaN,NaN
3782325,ZYG4MMKT847V,0f128fd98b4e3,1541634384,4,clickout item,NaN,BR,"Resende, Brazil",mobile,NaN,1089752|4103676|2033145|2684451|2053814|279089...,86|82|86|40|92|56|83|54|145|114|58|67|40|87|46...
3782326,ZYMVSZ5A3KQI,8cd16c29b733b,1541694988,1,search for destination,"Holiday City, USA",US,"Holiday City, USA",mobile,NaN,NaN,NaN
3782327,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,clickout item,NaN,US,"Holiday City, USA",mobile,NaN,364796|1299248|4891790|381296|1345175|9647370,92|52|92|89|59|275
3782334,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,46149|109974|46119|8333280|12455|1185556|84002...,138|138|156|153|128|202|145|137|105|68|133|167...

In [0]:
df_target = f.get_submission_target(df_mono)

In [0]:
df_target

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
8,009RGHI3G9A3,f05ab0de907e2,1541570940,2,clickout item,NaN,IN,"Nathdwara, India",mobile,NaN,10884872|7065316,64|28
109,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,13361|5647680|116764|898719|8276346|9168|19325...,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...
138,03VT0ODUTZB0,725e8adf70e86,1541632490,23,clickout item,NaN,UK,"Warrington, United Kingdom",desktop,NaN,109938|164193|632366|1362450|1070666|164220|11...,45|67|78|60|58|57|86|68|57|55|148|92|66|55|61|...
319,05BAHQHA5RCI,9f279162e8d5c,1541633993,5,clickout item,NaN,DE,"Ulm, Germany",tablet,Best Value,2755290|14054|10243166|3498770|726906|2616752|...,59|86|70|58|86|58|58|57|78|68|55|90|79|64|112|...
447,091L4C793B1J,49816a95c986a,1541625659,63,clickout item,NaN,AR,"Bombinhas, Brazil",mobile,NaN,2504828|2578276|511676|2344190|1652507|3242334...,135|76|62|93|51|45|75|28|40|76|32|27|50|77|92|...
452,09X618WIVTP3,b1935d2a43d5e,1541688108,3,clickout item,NaN,MY,"Genting Highlands, Malaysia",mobile,NaN,1120687|2165594|5763948|519501|595286|3386520|...,39|76|78|55|87|38|47|143|57|53|21|8|78|17|59|1...
513,0BZN2KFMHLZF,d9497eeb946dc,1541668916,1,clickout item,NaN,BE,"Hasselt, Belgium",mobile,NaN,39730|133101|39758|7029236|455086|3887112|1070...,90|88|80|80|90|62|65|90|89|75|70|109|165|104|6...
546,0CN5A7BJZRGW,0b105be325b12,1541657496,33,clickout item,NaN,IN,"Bengaluru, India",desktop,NaN,998041|1389106|1400686|2216204|2394112|2817576...,11|47|23|19|12|8|16|16|23|16|18|19|15|22|103|2...
554,0D1XFBRWUX7Z,35e873299a45f,1541586069,1,clickout item,NaN,AU,"Sydney, Australia",mobile,NaN,54865|54803|54953|14211|95510|54838|54794|1484...,163|126|158|177|145|85|107|158|132|189|187|131...
597,0DJUQ92EQYM0,d2039eb924c5d,1541649689,3,clickout item,NaN,BR,"Águas Claras, Brazil",mobile,NaN,3145586|5157920|478986|3993110|478991|5790206|...,44|26|30|43|45|37|17|42|17|25|27|22|44|33|22|3...
598,0EPVF4QE049Q,11b583578f7f3,1541611766,1,clickout item,NaN,FI,"Seinäjoki, Finland",mobile,NaN,368306|369426|4916202|2045589|1328820|369421|1...,123|152|59|148|105|147|98|70|95|80|140
599,0GY71I4BUBQW,334177bbc6525,1541638087,1,clickout item,NaN,AU,"Rome, Italy",desktop,NaN,17112|1374294|17382|2321776|16895|17056|17108|...,81|95|126|79|186|112|53|112|56|214|142|77|71|1...
600,0H2RFN3FXM5A,e9fa318e4aad0,1541576918,1,clickout item,NaN,IN,"Bengaluru, India",mobile,NaN,1984531|4775794|1400686|930783|2612414|1199716...,37|16|19|50|148|16|157|14|21|19|14|16|16|22|13...
602,0HG5FZNPFDYC,db55ce2d55626,1541571390,2,clickout item,NaN,RU,"Rostov-on-Don, Russia",mobile,NaN,10001880|6452708|7492016|1048438|10127018|4726...,54|205|40|52|187|34|39|29|70|46|39|69|36|55|55...
604,0HPR8MG837GZ,9e3e3ac5954f3,1541648887,2,clickout item,NaN,BR,"Boston, USA",tablet,NaN,8504|8500|79307|76753|3248570|67924|9522612|56...,100|72|117|63|125|106|210|77|76|99|99|113|113|...
614,0I20KCPKN010,f7529e581ca06,1541579052,8,clickout item,NaN,IN,"Diu, India",mobile,NaN,1401168|1522957|6686816|1133827|2656700|266167...,46|72|52|172|60|60|81|42|36|78|63|42|83|63|37|...
682,0L2CALL26C66,59bfbcb10146d,1541593658,1,clickout item,NaN,PL,"Alicante, Spain",desktop,NaN,8194404|6721|6724|40109|40718|81021|110591|147...,30|36|42|88|46|85|49|57|45|49|56|53|37|63|127|...
801,0ME9OE1GS1Q9,7afb20460a368,1541591150,1,clickout item,NaN,BG,"Prague, Czech Republic",mobile,NaN,13699|100667|13673|111234|14680|920765|80376|8...,61|45|62|32|42|57|54|135|58|79|85|49|69|129|10...
813,0NK2TU8JS5IE,c0e1d70377e8d,1541586959,2,clickout item,NaN,AU,"Weipa, Australia",mobile,NaN,2188426|3092731,98|117
815,0NMWJUR0YYSU,e3e39b4041170,1541677811,2,clickout item,NaN,DE,"Frankenberg, Germany",mobile,NaN,433511|5166404|7215348|925835|406646|771938|11...,199|94|69|164|158|121|118|80|110|82|85|74|62|5...
1060,0Q3W4X8HG57M,51c88e49fb6dc,1541612840,1,clickout item,NaN,FR,"Hong Kong, Hong Kong",mobile,NaN,54096|54132|54027|1204728|99423|54125|54146|54...,281|367|313|225|210|398|442|255|381|340|380|30...
1062,0Q4LCRC7V5H5,2699fea9e59a3,1541663905,2,clickout item,NaN,MY,"Port Dickson, Malaysia",desktop,NaN,693816|8113288|8131766|2776330|4605858|2296560...,43|48|17|38|23|30|45|18|26|31|36|40|33|31|29|2...
1103,0RGUIOXR7DYF,097b0cbdbe440,1541560449,37,clickout item,NaN,MY,"Kota Kinabalu, Malaysia",mobile,NaN,1981215|3768768|2018159|1276965|164822|2547148...,12|11|10|12|10|12|11|10|11|12|11
1124,0RY7NT74TQWG,f76547b8210d2,1541685407,21,clickout item,NaN,BR,"Guararema, Brazil",desktop,Excellent Rating,1811271|8894580|6618188|1811733|104708|2318256...,27|32|33|28|47|23|47|20|23|31|21|23|35
1125,0S6ZR5UCAHUK,88fe3fde210f4,1541650657,1,clickout item,NaN,RO,"Sibiu, Romania",desktop,NaN,6919316|7902572|972027|1314825|1306503|7202328...,37|22|80|42|103|50|78|69|19|33|36|28|92|41|22|...
1130,0SCD8YVIKSN2,24d7d52ceab06,1541673353,5,clickout item,NaN,DE,"Dülmen, Germany",mobile,Sort By Popularity,418191|246536|162838|9194182|162832|5201550|33...,90|86|80|190|79|95|86|85|106|131|120|98|88|86|...
1138,0T44QW6172IY,fa85ee327cffd,1541695828,8,clickout item,NaN,US,"Philadelphia, USA",mobile,Sort by Price,943933|60404|64784|388551|10079426|63124|74433...,74|75|78|79|83|87|90|92|96|96|104|108|109|111|...
1139,0UCBRUGP6YHU,f57abecfdc90e,1541704893,1,clickout item,NaN,DE,"Antwerp, Belgium",desktop,NaN,8735372|54627|1583829|54776|54685|54640|14856|...,109|154|54|59|98|109|170|131|127|60|134|135|66...
1170,0UH2OWH5CNJT,8574da6940b75,1541555988,25,clickout item,NaN,MX,"Monterrey, Mexico",desktop,NaN,6626164|136945|42757|3515342|43098|4040620|423...,44|127|69|78|71|112|86|54|95|66|61|83|74|72|56...
1179,0XJ0Z6P56N9I,b41da7780da40,1541620930,1,clickout item,NaN,BR,"São Mateus, Brazil",mobile,NaN,5822472|8285932|2811558|8210882|2796007|149645...,65|30|18|32|21|42|37|53|53|36|28|35|29|29|25|3...
...,...,...,...,...,...,...,...,...,...,...,...,...
3781503,YS3FLB5P575R,6440175fa677d,1541685763,148,clickout item,NaN,UK,"Warsaw, Poland",desktop,5 Star|Hotel|4 Star|Very Good Rating|Focus on ...,93318|93268|127648|935243|106958|2254964|15407...,77|96|54|51|93|94|109|107|90|57|100|52|104|101...
3781509,YSD1A103Q1A9,6ab62ceba5600,1541708733,6,clickout item,NaN,BE,"Los Cristianos, Spain",tablet,Best Value,4241044|6465082|3568642|3869986|890743|95009|1...,57|63|70|85|96|81|72|104|79|80|120|68|83|109|9...
3781510,YT9L9JPJXIWX,a301d602d7e00,1541610753,1,clickout item,NaN,BR,"Capão da Canoa, Brazil",mobile,NaN,3178436|3806932|2812962|4758110|7206520|395499...,27|36|77|40|43|35|53|116|29|34|26|81|22|58|28|...
3781511,YTB80DPXL79J,64454c1037a44,1541697217,1,clickout item,NaN,BR,"Ilha Comprida, Brazil",mobile,NaN,2676734|2811468|4538600|2651474|2681772|402594...,55|54|49|75|62|40|58|35|45|34|50|33|35|35
3781535,YXRHSL1LKNK1,b45aa1f490fe7,1541659382,11,clickout item,NaN,AU,"Sorrento, Australia",tablet,NaN,2773834|1979453|8128208|9651516|2941382|516194...,232|224|290|518|230|313|117|208|220|3941
3781536,YZHZ89YNHQZG,1e09eb2d72569,1541609674,1,clickout item,NaN,IT,"Puerto de la Cruz, Spain",mobile,NaN,7344|1223232|4143556|7347|15973|7361|15970|942...,95|135|82|77|91|85|112|70|71|95|81|66|95|114|7...
3781584,Z3DOMS0LB5VR,9b797a8304c0d,1541636098,3,clickout item,NaN,BR,"Serra, Brazil",mobile,NaN,2509802|2272964|3487672|7296338|9612210,119|104|117|59|164
3781623,Z3X7FGQV8DLZ,afb85a31ceff8,1541703091,3,clickout item,NaN,GR,"Volos, Greece",desktop,NaN,2032009|2026501|9906640|8105540|10595106|10048...,54|70|68|65|79|51|68|78|86|90|96|79|57
3781632,Z4U39CMNA0KC,f10a96cdd9ab6,1541647890,9,clickout item,NaN,IN,"Patiala, India",mobile,Sort by Price,4601590|7184724|5931996|3914536|7188488|100637...,5|5|5|5|6|6|7|7|8|8|9|9|9|10|10|10|10|10|10|11...
3781663,Z5HHW9GPWTVI,42642e9b52a8d,1541636572,31,clickout item,NaN,BR,"Guaxupé, Brazil",mobile,NaN,6475490|2579644,44|37
3781665,Z5OLI4N9BZ58,460a7458419b8,1541587762,1,clickout item,NaN,JP,"Kyoto, Japan",desktop,NaN,125092|818241|346866|103474|103543|2155888|164...,132|62|135|131|132|111|139|114|124|111|173|827...
3781666,Z6S5ELLKWH9U,b4cb947d63b06,1541642593,1,clickout item,NaN,NL,"Kralendijk, BES Islands",mobile,NaN,6893878|30595|5963500|6931536|975701|30599|877...,156|204|83|120|160|362|142|211|75|161|169|99|9...
3781668,Z6UH43QKBEFA,1a185e56b1687,1541592222,2,clickout item,NaN,AR,"Florianópolis, Brazil",desktop,NaN,5088964|861491|104832|478996|1330207|1862179|2...,58|115|748|178|200|166|77|291|103|106|166|125|...
3781673,Z7H6WZBWLCXT,5d6cc2ee3db46,1541631030,2,clickout item,NaN,BR,"Fortaleza, Brazil",mobile,NaN,104802|5032060|104867|104773|104939|104505|104...,71|99|98|89|139|70|90|103|115|86|113|89|48|53|...
3781687,Z8R3PNWG66WC,037d21739ccad,1541672836,14,clickout item,NaN,IT,"Amsterdam, Netherlands",mobile,NaN,1719593|3152692|4345706|3154396|42101|147253|1...,756|1177|254|986|962|724|169|534|690|310|359|2...
3781688,Z9GZ0O9E98XH,1694bed3ee9fb,1541667268,1,clickout item,NaN,AU,"Adelaide, Australia",desktop,NaN,667061|101857|995701|14848|3923476|54864|10923...,96|86|89|140|80|95|168|73|46|82|127|210|89|89|...
3781690,ZFD2YAQS3YX4,1e7237d9f35a8,1541709847,2,clickout item,NaN,BR,"São Paulo, Brazil",desktop,NaN,104912|5816566|478966|104607|104539|104710|597...,138|365|144|136|183|79|84|457|96|216|104|129|1...
3781709,ZJDPHM5DWJCD,e1b43bf209d50,1541577899,1,clickout item,NaN,BE,"Grindelwald, Switzerland",mobile,NaN,15953|1362025|15233|15955|1008989|7300410|1410...,134|148|212|239|64|105|126|564|126|564|709|218...
3781740,ZN0MI3V8DU6I,eec026e9dd8d9,1541560976,18,clickout item,NaN,US,"Vernon, USA",desktop,NaN,374956|620556|5964090|2506754|7846536|393276|2...,139|118|87|79|208|153|96|219|118
3781741,ZN7BDD39Y83X,929b6ba33334d,1541617907,1,clickout item,NaN,UK,"Glasgow, United Kingdom",mobile,NaN,152500|18512|627451|1061780|655466|2177802|123...,56|47|45|39|54|36|41|49|37|44|56|53|57|56|39|5...
3781776,ZT722F7KOKI8,66c459fc5f1d5,1541569655,1,clickout item,NaN,MX,"Chetumal, Mexico",mobile,NaN,2752786|42775|2777094|2028173|2637405|3140790|...,43|42|66|28|51|77|70|82|35|36|62|26|24|37|28|2...
3781780,ZU64EXB7HUSC,a12e64eb21788,1541618644,4,clickout item,NaN,US,"Victoria, Canada",desktop,NaN,44282|44410|44182|837166|1353966|44243|44679|4...,237|169|126|94|133|186|113|286|117|144|181|99|...
3781788,ZUCX42KNP5CA,911f86ae3cf64,1541678577,8,clickout item,NaN,JP,"Sasebo, Japan",desktop,Sort by Price,1738509|1738515|7689134|2018845|1179138|106494...,54|100|108|116|135|154|192|208|216|217|249|269...
3781790,ZV68634ROL49,4f5808cfa765b,1541699124,2,clickout item,NaN,IN,"Mussoorie, India",mobile,NaN,2841397|1005131|2378072|2378074|2643434|312778...,17|29|7|38|8|34|22|21|73|29|7|18|12|40|33|18|2...
3781839,ZVTSO44R1US2,ba077694ccf39,1541673409,49,clickout item,NaN,JP,"Sapporo, Japan",desktop,Hotel|Resort|Best Value|Hammam,5863172|494271|1042070|103453|9327438|2111024|...,72|90|100|92|81|86|92|83|81|100|105|104|95|87|...
3781840,ZVUSADAHBEMO,f5f4f9aa82b44,1541678661,1,clickout item,NaN,DE,"Grainau, Germany",desktop,NaN,51656|96015|52072|5465|5470|5484|117981|255274...,146|200|124|99|88|133|112|85|79|95|87|95|95|91...
3781846,ZWD4F2A7H5EK,3e4fdd55f6145,1541670697,2,clickout item,NaN,IT,"Milan, Italy",desktop,NaN,20259|20339|20363|20400|20407|954207|20564|202...,77|73|77|66|84|22|86|76|77|78|81|74|94|84|74|7...
3782325,ZYG4MMKT847V,0f128fd98b4e3,1541634384,4,clickout item,NaN,BR,"Resende, Brazil",mobile,NaN,1089752|4103676|2033145|2684451|2053814|279089...,86|82|86|40|92|56|83|54|145|114|58|67|40|87|46...
3782327,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,clickout item,NaN,US,"Holiday City, USA",mobile,NaN,364796|1299248|4891790|381296|1345175|9647370,92|52|92|89|59|275
3782334,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,46149|109974|46119|8333280|12455|1185556|84002...,138|138|156|153|128|202|145|137|105|68|133|167...

In [0]:
df_expl = f.explode(df_target, "impressions")

In [0]:
df_expl

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,prices,impressions
0,009RGHI3G9A3,f05ab0de907e2,1541570940,2,clickout item,NaN,IN,"Nathdwara, India",mobile,NaN,64|28,10884872
1,009RGHI3G9A3,f05ab0de907e2,1541570940,2,clickout item,NaN,IN,"Nathdwara, India",mobile,NaN,64|28,7065316
2,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,13361
3,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,5647680
4,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,116764
5,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,898719
6,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,8276346
7,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,9168
8,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,1932523
9,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,1746699
10,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,3184770
11,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,2029079
12,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,9663674
13,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,5773306
14,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,97047
15,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,2859080
16,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,2552912
17,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,37717
18,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,4500498
19,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,4957186
20,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,96783
21,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,2025847
22,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,2678430
23,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,94472
24,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,9500346
25,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,5055970
26,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,1293576
27,03VT0ODUTZB0,725e8adf70e86,1541632490,23,clickout item,NaN,UK,"Warrington, United Kingdom",desktop,NaN,45|67|78|60|58|57|86|68|57|55|148|92|66|55|61|...,109938
28,03VT0ODUTZB0,725e8adf70e86,1541632490,23,clickout item,NaN,UK,"Warrington, United Kingdom",desktop,NaN,45|67|78|60|58|57|86|68|57|55|148|92|66|55|61|...,164193
29,03VT0ODUTZB0,725e8adf70e86,1541632490,23,clickout item,NaN,UK,"Warrington, United Kingdom",desktop,NaN,45|67|78|60|58|57|86|68|57|55|148|92|66|55|61|...,632366
...,...,...,...,...,...,...,...,...,...,...,...,...
3492986,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,clickout item,NaN,US,"Holiday City, USA",mobile,NaN,92|52|92|89|59|275,1299248
3492987,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,clickout item,NaN,US,"Holiday City, USA",mobile,NaN,92|52|92|89|59|275,4891790
3492988,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,clickout item,NaN,US,"Holiday City, USA",mobile,NaN,92|52|92|89|59|275,381296
3492989,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,clickout item,NaN,US,"Holiday City, USA",mobile,NaN,92|52|92|89|59|275,1345175
3492990,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,clickout item,NaN,US,"Holiday City, USA",mobile,NaN,92|52|92|89|59|275,9647370
3492991,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,46149
3492992,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,109974
3492993,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,46119
3492994,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,8333280
3492995,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,12455
3492996,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,1185556
3492997,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,8400220
3492998,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,16674
3492999,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,344771
3493000,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,46144
3493001,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,1345912
3493002,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,46131
3493003,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,12476
3493004,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,12491
3493005,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,1204916
3493006,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,12451
3493007,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,12484
3493008,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,109971
3493009,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,46108
3493010,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,12480
3493011,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,895195
3493012,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,106848
3493013,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,344761
3493014,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,2388239
3493015,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,148242

In [0]:
# reference에서 letter, nan 제거
def only_number(string):
  try:
    int(string)
    return int(string)
  except ValueError:
    return np.nan

In [0]:
df_mono['reference_int'] = df_mono.reference.apply(only_number)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [0]:
df_mono

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices,reference_int
7,009RGHI3G9A3,f05ab0de907e2,1541570935,1,interaction item info,7065316,IN,"Nathdwara, India",mobile,NaN,NaN,NaN,7065316.0
8,009RGHI3G9A3,f05ab0de907e2,1541570940,2,clickout item,NaN,IN,"Nathdwara, India",mobile,NaN,10884872|7065316,64|28,NaN
62,0339C84S24ET,3e7d55eae386f,1541622138,1,interaction item image,8511456,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,8511456.0
63,0339C84S24ET,3e7d55eae386f,1541622138,2,interaction item image,8511456,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,8511456.0
64,0339C84S24ET,3e7d55eae386f,1541622146,3,clickout item,8511456,TR,"Antalya, Turkey",mobile,NaN,10598152|7031496|7348404|5753730|7238840|69382...,16|58|22|50|28|39|22|158|43|30|17|76|22,8511456.0
65,0339C84S24ET,3e7d55eae386f,1541622335,4,search for poi,Antalya Expo Center,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,NaN
66,0339C84S24ET,3e7d55eae386f,1541622358,5,search for poi,Antalya Expo Center,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,NaN
67,0339C84S24ET,3e7d55eae386f,1541622381,6,interaction item image,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,4957186.0
68,0339C84S24ET,3e7d55eae386f,1541622381,7,interaction item image,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,4957186.0
69,0339C84S24ET,3e7d55eae386f,1541622391,8,interaction item info,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,4957186.0
70,0339C84S24ET,3e7d55eae386f,1541622515,9,interaction item image,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,4957186.0
71,0339C84S24ET,3e7d55eae386f,1541622515,10,interaction item image,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,4957186.0
72,0339C84S24ET,3e7d55eae386f,1541622525,11,interaction item rating,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,4957186.0
73,0339C84S24ET,3e7d55eae386f,1541622545,12,interaction item deals,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,4957186.0
74,0339C84S24ET,89171d441a304,1541615122,1,interaction item info,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,4957186.0
75,0339C84S24ET,89171d441a304,1541615132,2,interaction item rating,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,4957186.0
76,0339C84S24ET,89171d441a304,1541615142,3,interaction item deals,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,4957186.0
77,0339C84S24ET,89171d441a304,1541615193,4,interaction item image,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,4957186.0
78,0339C84S24ET,89171d441a304,1541615193,5,interaction item image,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,4957186.0
79,0339C84S24ET,89171d441a304,1541615201,6,interaction item image,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,4957186.0
80,0339C84S24ET,89171d441a304,1541615551,7,interaction item image,8160620,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,8160620.0
81,0339C84S24ET,89171d441a304,1541615551,8,interaction item image,8160620,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,8160620.0
82,0339C84S24ET,89171d441a304,1541615580,9,interaction item image,4957186,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,4957186.0
83,0339C84S24ET,89171d441a304,1541615655,10,interaction item image,37717,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,37717.0
84,0339C84S24ET,89171d441a304,1541615655,11,interaction item image,37717,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,37717.0
85,0339C84S24ET,89171d441a304,1541615665,12,interaction item image,37717,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,37717.0
86,0339C84S24ET,89171d441a304,1541615665,13,interaction item image,37717,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,37717.0
87,0339C84S24ET,89171d441a304,1541615665,14,interaction item image,37717,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,37717.0
88,0339C84S24ET,89171d441a304,1541615665,15,interaction item image,37717,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,37717.0
89,0339C84S24ET,89171d441a304,1541615665,16,interaction item image,37717,TR,"Antalya, Turkey",mobile,NaN,NaN,NaN,37717.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3781824,ZVTSO44R1US2,ba077694ccf39,1541673393,34,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN,494271.0
3781825,ZVTSO44R1US2,ba077694ccf39,1541673403,35,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN,494271.0
3781826,ZVTSO44R1US2,ba077694ccf39,1541673403,36,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN,494271.0
3781827,ZVTSO44R1US2,ba077694ccf39,1541673403,37,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN,494271.0
3781828,ZVTSO44R1US2,ba077694ccf39,1541673403,38,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN,494271.0
3781829,ZVTSO44R1US2,ba077694ccf39,1541673403,39,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN,494271.0
3781830,ZVTSO44R1US2,ba077694ccf39,1541673403,40,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN,494271.0
3781831,ZVTSO44R1US2,ba077694ccf39,1541673403,41,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN,494271.0
3781832,ZVTSO44R1US2,ba077694ccf39,1541673403,42,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN,494271.0
3781833,ZVTSO44R1US2,ba077694ccf39,1541673403,43,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN,494271.0
3781834,ZVTSO44R1US2,ba077694ccf39,1541673403,44,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN,494271.0
3781835,ZVTSO44R1US2,ba077694ccf39,1541673403,45,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN,494271.0
3781836,ZVTSO44R1US2,ba077694ccf39,1541673403,46,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN,494271.0
3781837,ZVTSO44R1US2,ba077694ccf39,1541673403,47,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN,494271.0
3781838,ZVTSO44R1US2,ba077694ccf39,1541673403,48,interaction item image,494271,JP,"Sapporo, Japan",desktop,NaN,NaN,NaN,494271.0
3781839,ZVTSO44R1US2,ba077694ccf39,1541673409,49,clickout item,NaN,JP,"Sapporo, Japan",desktop,Hotel|Resort|Best Value|Hammam,5863172|494271|1042070|103453|9327438|2111024|...,72|90|100|92|81|86|92|83|81|100|105|104|95|87|...,NaN
3781840,ZVUSADAHBEMO,f5f4f9aa82b44,1541678661,1,clickout item,NaN,DE,"Grainau, Germany",desktop,NaN,51656|96015|52072|5465|5470|5484|117981|255274...,146|200|124|99|88|133|112|85|79|95|87|95|95|91...,NaN
3781845,ZWD4F2A7H5EK,3e4fdd55f6145,1541670674,1,interaction item info,20259,IT,"Milan, Italy",desktop,NaN,NaN,NaN,20259.0
3781846,ZWD4F2A7H5EK,3e4fdd55f6145,1541670697,2,clickout item,NaN,IT,"Milan, Italy",desktop,NaN,20259|20339|20363|20400|20407|954207|20564|202...,77|73|77|66|84|22|86|76|77|78|81|74|94|84|74|7...,NaN
3782318,ZXGCLNDBW84E,53cb30d7ca9c6,1541702970,1,search for destination,"Fortaleza, Brazil",BR,"Fortaleza, Brazil",desktop,NaN,NaN,NaN,NaN
3782319,ZXGCLNDBW84E,53cb30d7ca9c6,1541703012,2,search for destination,"Porto Seguro, Brazil",BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN,NaN
3782320,ZXGCLNDBW84E,53cb30d7ca9c6,1541703034,3,search for item,477936,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN,477936.0
3782321,ZXGCLNDBW84E,53cb30d7ca9c6,1541703038,4,clickout item,477936,BR,"Porto Seguro, Brazil",desktop,NaN,477936|1326068|1668443|503361|1886269|478656|5...,42|49|36|170|40|45|38|140|60|57|75|53|153|71|6...,477936.0
3782322,ZYG4MMKT847V,0f128fd98b4e3,1541634316,1,search for destination,"Resende, Brazil",BR,"Resende, Brazil",mobile,NaN,NaN,NaN,NaN
3782323,ZYG4MMKT847V,0f128fd98b4e3,1541634383,2,interaction item image,1089752,BR,"Resende, Brazil",mobile,NaN,NaN,NaN,1089752.0
3782324,ZYG4MMKT847V,0f128fd98b4e3,1541634383,3,interaction item image,1089752,BR,"Resende, Brazil",mobile,NaN,NaN,NaN,1089752.0
3782325,ZYG4MMKT847V,0f128fd98b4e3,1541634384,4,clickout item,NaN,BR,"Resende, Brazil",mobile,NaN,1089752|4103676|2033145|2684451|2053814|279089...,86|82|86|40|92|56|83|54|145|114|58|67|40|87|46...,NaN
3782326,ZYMVSZ5A3KQI,8cd16c29b733b,1541694988,1,search for destination,"Holiday City, USA",US,"Holiday City, USA",mobile,NaN,NaN,NaN,NaN
3782327,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,clickout item,NaN,US,"Holiday City, USA",mobile,NaN,364796|1299248|4891790|381296|1345175|9647370,92|52|92|89|59|275,NaN
3782334,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,46149|109974|46119|8333280|12455|1185556|84002...,138|138|156|153|128|202|145|137|105|68|133|167...,NaN

In [0]:
def reference_count(df):
  multi = df.groupby(df.session_id).reference_int.value_counts() # na값 drop by default 
  df_out = pd.DataFrame(multi).rename(columns = {'reference_int':'ref_count'}).reset_index()
  return df_out

In [0]:
df_ref_count = reference_count(df_mono)

In [0]:
df_ref_count

           session_id  reference_int  ref_count
0       0001d7853e07d       888605.0          2
1       0001d7853e07d       906385.0          2
2       0003005fe4aa2      2418986.0          1
3       00035287b3cd6       449196.0         21
4       0003e88695444      8317502.0          1
5       0004913471800      2362196.0         21
6       0004913471800      2572382.0          1
7       000518a3ad14d      1001367.0          1
8       0006fad60bc56       106173.0          3
9       000737a92bc59      1776289.0         28
10      000737a92bc59      3144968.0         13
11      000948ebfde5d        76021.0          1
12      0009972b1cf2c        70300.0          2
13      000b098df63ce      1314498.0         17
14      000bbfa1bf0a4         6493.0         19
15      000bbfa1bf0a4        52099.0         18
16      000bbfa1bf0a4         5190.0         16
17      000bbfa1bf0a4       339676.0         12
18      000bbfa1bf0a4         6494.0         11
19      000bbfa1bf0a4         6495.0         11
20      000bbfa1bf0a4         6500.0         10
21      000bbfa1bf0a4        51706.0         10
22      000bbfa1bf0a4         5188.0          9
23      000bbfa1bf0a4         6492.0          8
24      000bbfa1bf0a4      3490822.0          6
25      000d6d5317c35      1890749.0         17
26      000d6d5317c35      2707620.0         13
27      000d6d5317c35       104730.0         12
28      000da53957fa7      4871050.0          2
29      000dbf48935c6      1668749.0         17
...               ...            ...        ...
123191  ffee2b7b1057c      2501350.0          1
123192  fff2339d40cac        40057.0          2
123193  fff2339d40cac        40728.0          2
123194  fff322eb30e01      5191346.0         31
123195  fff322eb30e01        13347.0          1
123196  fff37d530cfbe      3892430.0          1
123197  fff47ac2561d7      1282274.0          1
123198  fff4e1a88883d      6001834.0          2
123199  fff4e1a88883d      5060220.0          1
123200  fff4e1a88883d      6482688.0          1
123201  fff5814e50272        18208.0          5
123202  fff5814e50272       153359.0          1
123203  fff9207e243bf      4132218.0          1
123204  fff9207e243bf      7717508.0          1
123205  fff9858a4e6c4      1489505.0          2
123206  fff9addd1e78b       124097.0          2
123207  fff9fb153e20b      6655632.0          7
123208  fffa4666b0807        54589.0          4
123209  fffc62338f175      2053936.0          5
123210  fffc6a16af7d0      6852746.0          1
123211  fffcb835d5262       147731.0          3
123212  fffd4213e2767      3854692.0          7
123213  fffd47c879d4e        53996.0          1
123214  ffffd16222b90      2709816.0         24
123215  ffffd16222b90      2651645.0          2
123216  j00jha5h6hquv       120786.0         38
123217  j00jha5h6hquv      1499553.0          1
123218  m35905qbciei4       478321.0         34
123219  mck3hrr30lm51      1083616.0         34
123220  nlualuchh7j46      2038143.0         42

[123221 rows x 3 columns]

In [0]:
df_expl

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,prices,impressions
0,009RGHI3G9A3,f05ab0de907e2,1541570940,2,clickout item,NaN,IN,"Nathdwara, India",mobile,NaN,64|28,10884872
1,009RGHI3G9A3,f05ab0de907e2,1541570940,2,clickout item,NaN,IN,"Nathdwara, India",mobile,NaN,64|28,7065316
2,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,13361
3,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,5647680
4,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,116764
5,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,898719
6,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,8276346
7,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,9168
8,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,1932523
9,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,1746699
10,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,3184770
11,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,2029079
12,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,9663674
13,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,5773306
14,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,97047
15,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,2859080
16,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,2552912
17,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,37717
18,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,4500498
19,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,4957186
20,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,96783
21,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,2025847
22,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,2678430
23,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,94472
24,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,9500346
25,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,5055970
26,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...,1293576
27,03VT0ODUTZB0,725e8adf70e86,1541632490,23,clickout item,NaN,UK,"Warrington, United Kingdom",desktop,NaN,45|67|78|60|58|57|86|68|57|55|148|92|66|55|61|...,109938
28,03VT0ODUTZB0,725e8adf70e86,1541632490,23,clickout item,NaN,UK,"Warrington, United Kingdom",desktop,NaN,45|67|78|60|58|57|86|68|57|55|148|92|66|55|61|...,164193
29,03VT0ODUTZB0,725e8adf70e86,1541632490,23,clickout item,NaN,UK,"Warrington, United Kingdom",desktop,NaN,45|67|78|60|58|57|86|68|57|55|148|92|66|55|61|...,632366
...,...,...,...,...,...,...,...,...,...,...,...,...
3492986,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,clickout item,NaN,US,"Holiday City, USA",mobile,NaN,92|52|92|89|59|275,1299248
3492987,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,clickout item,NaN,US,"Holiday City, USA",mobile,NaN,92|52|92|89|59|275,4891790
3492988,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,clickout item,NaN,US,"Holiday City, USA",mobile,NaN,92|52|92|89|59|275,381296
3492989,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,clickout item,NaN,US,"Holiday City, USA",mobile,NaN,92|52|92|89|59|275,1345175
3492990,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,clickout item,NaN,US,"Holiday City, USA",mobile,NaN,92|52|92|89|59|275,9647370
3492991,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,46149
3492992,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,109974
3492993,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,46119
3492994,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,8333280
3492995,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,12455
3492996,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,1185556
3492997,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,8400220
3492998,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,16674
3492999,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,344771
3493000,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,46144
3493001,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,1345912
3493002,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,46131
3493003,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,12476
3493004,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,12491
3493005,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,1204916
3493006,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,12451
3493007,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,12484
3493008,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,109971
3493009,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,46108
3493010,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,12480
3493011,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,895195
3493012,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,106848
3493013,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,344761
3493014,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,2388239
3493015,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,138|138|156|153|128|202|145|137|105|68|133|167...,148242

In [0]:
def ref_recommendation(df_expl, df_ref_count):
    """Calculate recommendations based on the number of being referred.
    The final data frame will have an impression list sorted according to the number of being referred item.
    :param df_expl: Data frame with exploded impression list
    :param df_pop: Data frame with session, items and number of being referred
    :return: Data frame with sorted impression list according to the number of being referred in df_ref_count.
    """
    GR_COLS =  ["user_id", "session_id", "timestamp", "step"]
    
    df_expl_clicks = (
        df_expl[GR_COLS + ["impressions"]]
        .merge(df_ref_count,
               left_on=["session_id", "impressions"],
               right_on=["session_id", "reference_int"],
               how="left")
    )

    df_out = (
        df_expl_clicks
        .assign(impressions=lambda x: x["impressions"].apply(str))
        .sort_values(GR_COLS + ["ref_count"],
                     ascending=[True, True, True, True, False])
    )

    df_out = f.group_concat(df_out, GR_COLS, "impressions")
    df_out.rename(columns={'impressions': 'item_recommendations'}, inplace=True)

    return df_out

In [0]:
df_out = ref_recommendation(df_expl, df_ref_count)

In [0]:
df_out

,user_id,session_id,timestamp,step,item_recommendations
0,000324D9BBUC,89643988fdbfb,1541593942,10,1000915 1241375 923407 1729121 1050792 97171 3...
1,0004Q49X39PY,9de47d9a66494,1541641157,1,2213014 3184842 10213134 4504242 4486372 38120...
2,0004Q49X39PY,beea5c27030cb,1541561202,1,3812004 3505150 3202894 2292254 1984229 222789...
3,000GO9NY6P4M,55dbafdbb9bab,1541594662,2,319866 157710 1287958 160577 1618677 7231396 4...
4,000JB0UNEH23,7df07dc9fe26e,1541618174,1,2184212 2756867 2909994 4063406 3874514 950324...
5,00130PO6XSZR,0d5fe519827f3,1541701777,1,9416426 1954105 2909952 3050704 5814182 582821...
6,0015X90DOWT1,6ed36662b8da9,1541617000,3,80407 100670 136175 14243 80395 6722770 80397 ...
7,0017FIR55K7R,f2787447a02eb,1541607094,3,5739078 1994981 1189730 2816146 1189734 401516...
8,001D536Q4S8D,7480cfb2714a9,1541705106,1,2393760 2282708 3181794 3819674 5817342 722427...
9,001I0INS8EBP,8db447f4acfd4,1541665607,7,1420813 1829987 1433506 1047536 129346 3045661...
10,001LT4KVZ14I,09b977ff40a95,1541599141,5,3892430 127132 1548923 5162722 127125 1472107 ...
11,001P60T145X4,e10bbb9cf23a0,1541574899,2,1906153 8427842 3831704
12,001TD1JLUE4D,f2e3d55df14e6,1541707452,9,2810310 2798588 4509166 5150502 5434014 937236...
13,001WP37I7I1T,64c1bf66c64f8,1541573542,274,1515919 2857726 4658158 6256850 3447370 643491...
14,00210VAF61G5,15ed833cebd56,1541624585,3,2897075 9041798 1157009 10878252 2519966 71957...
15,0023UTXOFLJP,65784fbe9fff7,1541719700,3,7486 7500 7489 1447229 151992 1322948 809286 8...
16,0028DFS9FKIP,3f9358159498f,1541581159,2,103561 103480 1031930 1153224 347086 3079114 1...
17,0029FEXX2R5F,e81a933be3c48,1541565220,25,100222 34436 34437 2593763 32674 34432 5963164...
18,002BISXP1U1Q,0b422b13e1e46,1541665337,1,503071 1128018 1155657 1629065 1193542 1500191...
19,002DU3SR91P5,90caccfd7b855,1541597209,1,2165232 1024884 1024862 2165230 1024848 199626...
20,002EOD1A549M,0d75108975d46,1541707419,2,79435 68929 1082476 1082474 73465 80017 78154 ...
21,002H6CBQZ649,c55d4dbb5f384,1541674133,27,72230 5100962 5211500 63832 8107 148437 63456 ...
22,002N9ZH16N1R,7ad39a3e82f1e,1541668143,1,6688304 3844380 3793522 4016810 2656440 938753...
23,002NTOHZ5ED7,6802efcade7c0,1541642190,78,9559738 79160 128153 6626206 355316 1333874 45...
24,002T8HU4LZAS,e84fec9a8379c,1541656005,1,693436 103629 9121108 1148138 1015595 979131 5...
25,002XKX4GXZ4T,c8e46d42e27b2,1541705102,3,81311 2799306 656606 2632774 1758933 1332072 2...
26,002YMA0MBZRU,6a0ab34c0b3a9,1541672567,1,6828466 6317796 1890471 2642404 2618980 946028...
27,0034995IC4NO,ab70c737cf3d3,1541631186,1,42865 1273638 5455826 6276738 959499 4485832 4...
28,003A3JYSRGG8,b1635ca02e95d,1541698153,1,2813162 8450588 4400808 5173944 2814200 950149...
29,003B331S7UDW,9068c86d24d71,1541555663,1,1775983 1954055 7830188 4655114 3994056 197654...
...,...,...,...,...,...
154123,ZZHGH47FAML8,f298ea2e3b519,1541582596,1,1143478 95754 1667507 531101 1027852 1079744 5...
154124,ZZHUJL6WCXQK,16f36a84b13b8,1541582679,1,103452 891093 8805412 103484 1127559 1049928 1...
154125,ZZIKR683WHQL,6a99051badce3,1541702493,2,43772 101044 43445 1322260 3134952 5142740 446...
154126,ZZJHEJ663XEF,b29cf0e3112ac,1541628610,12,4007792 2252706 2249882 2252498 587116 4055748...
154127,ZZJWIGQEMLUY,9dfa0e82f0123,1541714089,1,350401 8452302 228481 226551 4454540 164126 38...
154128,ZZKKPPAA61F8,2a6e7df839b0d,1541615917,3,2282520 2897075 7195782 9041798 1157009 251996...
154129,ZZMPQ395DO4E,3909c7b6e7945,1541652803,1,2716694 1080740 3803986 9636758 1182166 134469...
154130,ZZMQSNA3X9NU,af3fc337105e6,1541689663,1,70127 1294330 1285742 76691 78295 1762659 7434...
154131,ZZN37EJFUKM6,c3850579ebc1f,1541636980,1,2865687 3211734 4041236 3244271 127713 489096 ...
154132,ZZO3PB6GNFHV,62e802015a6a9,1541625314,1,40788 7452 80884 100913 1411963 40485 40759 40...
154133,ZZOYWHF1QY4H,b38a43e576355,1541719570,1,42613 43031 128815 34354 914361 32822 4858646 ...
154134,ZZP3ZQ4YM0ML,2fe15092a93b4,1541683428,1,1772821 349051 897983 43001 1722351 42442 4288...
154135,ZZQP8L1GXPKM,e2cb57fc108bc,1541587680,4,1240081 5647680 8276346 7118816 37714 3184770 ...
154136,ZZQZR8KSXBHW,e56dcaa88dc65,1541601042,10,3371792 5384 5398 53348 3133508 13862 5367 533...
154137,ZZREITSO0Z1K,55cff60d53c77,1541680007,1,42295 100623 33011 33024 33023 6065970 148580 ...
154138,ZZRJ4VP7NV4B,2180d3508a53e,1541594816,1,6704254 976227 1034346 1336768 2295478 2666986...
154139,ZZSHMZO6F36T,4150ea910c201,1541572362,1,7560 5739690 5742058 7538 48199 84600 98257 10...
154140,ZZSZN2E4ANXP,8023355febecb,1541715046,1,85482 33271 2423450 3155562 1708563 42214 4220...
154141,ZZTADJSKLQP8,c16f87d4b9ae0,1541610415,1,75837 112922 55675 61611 66939 107424 66946 68...
154142,ZZTGL330L8UH,14586a0acf80f,1541591520,3,9161418 5519792 4939140 8694234 5417236 348530...
154143,ZZV1ZO0IG4L2,341f161ea7bdb,1541590185,18,2662314 2662332 5218264 2887560 10585474 10595...
154144,ZZW77165VCI9,9dcbb235a6119,1541676035,16,46123 46127 46061 401081 148247 148241 148245 ...
154145,ZZWVBPY9GVOO,99b1a68b0b38e,1541680100,1,9730654 109337 8745456 104497 4204412 9633862 ...
154146,ZZX96IB781KD,26cfca16335a5,1541604085,5,9969810 2547826 5012782 694946 808826 1156335 ...
154147,ZZY0EXJHC765,602ac5b7a9a46,1541715925,2,1776243 6834890 9771364 8791726 8147418 698307...
154148,ZZY52IA5S865,ddaa2c37a3e72,1541598414,2,8784358 9468046 7004198 6338122 2501350 827849...
154149,ZZYQ7N5SPOLU,73bdd2bf4dd3f,1541579743,3,4600550 7313132 4480888 4519930 4531914 937385...
154150,ZZYQV7A1F50E,5fc0d6917f23c,1541594775,95,9362166 2327954 103949 8154570 22837 7968826 2...
154151,ZZZ7ZXP3KT8R,57321063674f0,1541629994,2,103562 2266812 347086 2071694 1153224 6892872 ...
154152,ZZZ8F76XAJ4M,20400210189ec,1541579657,1,82356 99675 99858 50085 48726 1158914 12102 82...

In [0]:
df_out.to_csv(path + 'mono.csv')

## CASE 2
clickout 개수가 2개 이상인 session 

*  df_many : 한 session내에서 clickout 횟수가 1번 이상인 session들의 df
* *주의* : clickout끼리 붙어있는 경우와 clickout끼리 떨어진 경우 구분해야한다.  [접근방법]  pure (session별 모든 reference) - previous (clickout한 reference)

In [0]:
def many(df):
  s = (df.loc[df.action_type == 'clickout item'].groupby('session_id').action_type.count() != 1)
  many_sess_index = s.index[s].to_list() # return session_id index
  df_many = df.loc[df.session_id.isin(many_sess_index)]
  
  return df_many

In [0]:
df_many = many(df_test)

In [22]:
df_many

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
0,004A07DM0IDW,1d688ec168932,1541555614,1,interaction item image,2059240,CO,"Santa Marta, Colombia",mobile,NaN,NaN,NaN
1,004A07DM0IDW,1d688ec168932,1541555614,2,interaction item image,2059240,CO,"Santa Marta, Colombia",mobile,NaN,NaN,NaN
2,004A07DM0IDW,1d688ec168932,1541555696,3,clickout item,1050068,CO,"Santa Marta, Colombia",mobile,NaN,2059240|2033381|1724779|127131|399441|103357|1...,70|46|48|76|65|65|106|66|87|43|52|44|60|61|50|...
3,004A07DM0IDW,1d688ec168932,1541555707,4,clickout item,1050068,CO,"Santa Marta, Colombia",mobile,NaN,2059240|2033381|1724779|127131|399441|103357|1...,70|46|48|76|65|65|106|66|87|43|52|44|60|61|50|...
4,004A07DM0IDW,1d688ec168932,1541555717,5,clickout item,1050068,CO,"Santa Marta, Colombia",mobile,NaN,2059240|2033381|1724779|127131|399441|103357|1...,70|46|48|76|65|65|106|66|87|43|52|44|60|61|50|...
5,004A07DM0IDW,1d688ec168932,1541555792,6,clickout item,3241426,CO,"Santa Marta, Colombia",mobile,NaN,2059240|2033381|1724779|127131|399441|103357|1...,70|46|48|76|65|65|106|66|87|43|52|44|60|61|50|...
6,004A07DM0IDW,1d688ec168932,1541555799,7,clickout item,NaN,CO,"Santa Marta, Colombia",mobile,NaN,2059240|2033381|1724779|127131|399441|103357|1...,70|46|48|76|65|65|106|66|87|43|52|44|60|61|50|...
9,00Y1Z24X8084,26b6d294d66e7,1541651766,1,clickout item,3843244,PH,"Iloilo City, Philippines",mobile,NaN,2714480|4476010|3843244|3833012|9017890|198100...,74|14|22|38|55|44|28|34|23|27|12|108|19|21|36|...
10,00Y1Z24X8084,26b6d294d66e7,1541651823,2,clickout item,NaN,PH,"Iloilo City, Philippines",mobile,NaN,2714480|4476010|3843244|3833012|9017890|198100...,74|14|22|38|55|44|28|34|23|27|12|108|19|21|36|...
11,01V3WDTDM5CU,07628a0f5be0b,1541575493,1,change of sort order,interaction sort button,PL,"Wisla, Poland",mobile,NaN,NaN,NaN
12,01V3WDTDM5CU,07628a0f5be0b,1541575503,2,change of sort order,price only,PL,"Wisla, Poland",mobile,NaN,NaN,NaN
13,01V3WDTDM5CU,07628a0f5be0b,1541575503,3,filter selection,Sort by Price,PL,"Wisla, Poland",mobile,Sort by Price,NaN,NaN
14,01V3WDTDM5CU,07628a0f5be0b,1541575516,4,clickout item,2817590,PL,"Wisla, Poland",mobile,Sort by Price,3565720|2947584|4115018|2039671|3836538|801409...,16|18|20|21|22|22|28|28|28|30|30|33|33|35|35|3...
15,01V3WDTDM5CU,07628a0f5be0b,1541575643,5,clickout item,NaN,PL,"Wisla, Poland",mobile,Sort by Price,3565720|2947584|4115018|2039671|3836538|801409...,16|18|20|21|22|22|28|28|28|30|30|33|33|35|35|3...
16,02AOAVF9PVYH,4a01c3afbc224,1541680071,1,search for destination,"Yokohama, Japan",JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
17,02AOAVF9PVYH,4a01c3afbc224,1541680083,2,interaction item image,552311,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
18,02AOAVF9PVYH,4a01c3afbc224,1541680083,3,interaction item image,552311,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
19,02AOAVF9PVYH,4a01c3afbc224,1541680085,4,interaction item image,552311,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
20,02AOAVF9PVYH,4a01c3afbc224,1541680096,5,interaction item image,552311,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
21,02AOAVF9PVYH,4a01c3afbc224,1541680104,6,filter selection,Hotel,JP,"Yokohama, Japan",desktop,Hotel|Resort,NaN,NaN
22,02AOAVF9PVYH,4a01c3afbc224,1541680104,7,filter selection,Resort,JP,"Yokohama, Japan",desktop,Hotel|Resort,NaN,NaN
23,02AOAVF9PVYH,4a01c3afbc224,1541680261,8,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
24,02AOAVF9PVYH,4a01c3afbc224,1541680261,9,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
25,02AOAVF9PVYH,4a01c3afbc224,1541680271,10,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
26,02AOAVF9PVYH,4a01c3afbc224,1541680271,11,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
27,02AOAVF9PVYH,4a01c3afbc224,1541680271,12,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
28,02AOAVF9PVYH,4a01c3afbc224,1541680271,13,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
29,02AOAVF9PVYH,4a01c3afbc224,1541680271,14,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
30,02AOAVF9PVYH,4a01c3afbc224,1541680271,15,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
31,02AOAVF9PVYH,4a01c3afbc224,1541680271,16,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3782294,ZXGCLNDBW84E,e73c90b6f448e,1541696396,443,interaction item info,1953137,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782295,ZXGCLNDBW84E,e73c90b6f448e,1541696591,444,interaction item image,1668443,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782296,ZXGCLNDBW84E,e73c90b6f448e,1541696824,445,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782297,ZXGCLNDBW84E,e73c90b6f448e,1541696824,446,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782298,ZXGCLNDBW84E,e73c90b6f448e,1541696836,447,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782299,ZXGCLNDBW84E,e73c90b6f448e,1541696836,448,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782300,ZXGCLNDBW84E,e73c90b6f448e,1541696836,449,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782301,ZXGCLNDBW84E,e73c90b6f448e,1541696836,450,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782302,ZXGCLNDBW84E,e73c90b6f448e,1541696836,451,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782303,ZXGCLNDBW84E,e73c90b6f448e,1541696836,452,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782304,ZXGCLNDBW84E,e73c90b6f448e,1541696836,453,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782305,ZXGCLNDBW84E,e73c90b6f448e,1541696846,454,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782306,ZXGCLNDBW84E,e73c90b6f448e,1541696846,455,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782307,ZXGCLNDBW84E,e73c90b6f448e,1541696846,456,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782308,ZXGCLNDBW84E,e73c90b6f448e,1541696846,457,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782309,ZXGCLNDBW84E,e73c90b6f448e,1541696846,458,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782310,ZXGCLNDBW84E,e73c90b6f448e,1541696846,459,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782311,ZXGCLNDBW84E,e73c90b6f448e,1541696846,460,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782312,ZXGCLNDBW84E,e73c90b6f448e,1541696846,461,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782313,ZXGCLNDBW84E,e73c90b6f448e,1541696846,462,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782314,ZXGCLNDBW84E,e73c90b6f448e,1541696846,463,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782315,ZXGCLNDBW84E,e73c90b6f448e,1541696851,464,clickout item,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,1704073|2159352|2780354|1668443|2030611|103162...,78|71|46|36|28|40|50|20|37|29|51|33|80|51|78|7...
3782316,ZXGCLNDBW84E,e73c90b6f448e,1541699223,465,clickout item,916029,BR,"Porto Seguro, Brazil",desktop,NaN,916029|1650015|326846|503361|1326068|477936|38...,60|81|140|171|49|42|38|60|57|74|191|71|55|45|5...
3782317,ZXGCLNDBW84E,e73c90b6f448e,1541699269,466,clickout item,NaN,BR,"Porto Seguro, Brazil",desktop,NaN,916029|1650015|326846|503361|1326068|477936|38...,60|81|140|171|49|42|38|60|57|74|191|71|55|45|5...
3782328,ZZ39YE45SZIE,f5db4092ec9fc,1541551871,1,interaction item info,5779140,HK,"Taitung City, Taiwan",mobile,NaN,NaN,NaN
3782329,ZZ39YE45SZIE,f5db4092ec9fc,1541551888,2,interaction item image,2849116,HK,"Taitung City, Taiwan",mobile,NaN,NaN,NaN
3782330,ZZ39YE45SZIE,f5db4092ec9fc,1541551888,3,interaction item image,2849116,HK,"Taitung City, Taiwan",mobile,NaN,NaN,NaN
3782331,ZZ39YE45SZIE,f5db4092ec9fc,1541551891,4,clickout item,2849116,HK,"Taitung City, Taiwan",mobile,NaN,9925140|2625125|5779140|7365168|5849342|198775...,219|215|183|215|590|70|131|111|64|65|127|94|64...
3782332,ZZ39YE45SZIE,f5db4092ec9fc,1541551899,5,interaction item image,2849116,HK,"Taitung City, Taiwan",mobile,NaN,NaN,NaN
3782333,ZZ39YE45SZIE,f5db4092ec9fc,1541551945,6,clickout item,NaN,HK,"Taitung City, Taiwan",mobile,NaN,9925140|2625125|5779140|7365168|5849342|198775...,219|215|183|215|590|70|131|111|64|65|127|94|64...

In [0]:
df_many_with_clickout = df_many.loc[(df_many.action_type == "clickout item") & (df_many.reference.notnull())] # clickout row

In [0]:
df_many_no_clickout = df_test.iloc[df_many.index.difference(df_many_with_clickout.index)] # not clickout row

In [27]:
df_many_no_clickout

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
0,004A07DM0IDW,1d688ec168932,1541555614,1,interaction item image,2059240,CO,"Santa Marta, Colombia",mobile,NaN,NaN,NaN
1,004A07DM0IDW,1d688ec168932,1541555614,2,interaction item image,2059240,CO,"Santa Marta, Colombia",mobile,NaN,NaN,NaN
6,004A07DM0IDW,1d688ec168932,1541555799,7,clickout item,NaN,CO,"Santa Marta, Colombia",mobile,NaN,2059240|2033381|1724779|127131|399441|103357|1...,70|46|48|76|65|65|106|66|87|43|52|44|60|61|50|...
10,00Y1Z24X8084,26b6d294d66e7,1541651823,2,clickout item,NaN,PH,"Iloilo City, Philippines",mobile,NaN,2714480|4476010|3843244|3833012|9017890|198100...,74|14|22|38|55|44|28|34|23|27|12|108|19|21|36|...
11,01V3WDTDM5CU,07628a0f5be0b,1541575493,1,change of sort order,interaction sort button,PL,"Wisla, Poland",mobile,NaN,NaN,NaN
12,01V3WDTDM5CU,07628a0f5be0b,1541575503,2,change of sort order,price only,PL,"Wisla, Poland",mobile,NaN,NaN,NaN
13,01V3WDTDM5CU,07628a0f5be0b,1541575503,3,filter selection,Sort by Price,PL,"Wisla, Poland",mobile,Sort by Price,NaN,NaN
15,01V3WDTDM5CU,07628a0f5be0b,1541575643,5,clickout item,NaN,PL,"Wisla, Poland",mobile,Sort by Price,3565720|2947584|4115018|2039671|3836538|801409...,16|18|20|21|22|22|28|28|28|30|30|33|33|35|35|3...
16,02AOAVF9PVYH,4a01c3afbc224,1541680071,1,search for destination,"Yokohama, Japan",JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
17,02AOAVF9PVYH,4a01c3afbc224,1541680083,2,interaction item image,552311,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
18,02AOAVF9PVYH,4a01c3afbc224,1541680083,3,interaction item image,552311,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
19,02AOAVF9PVYH,4a01c3afbc224,1541680085,4,interaction item image,552311,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
20,02AOAVF9PVYH,4a01c3afbc224,1541680096,5,interaction item image,552311,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
21,02AOAVF9PVYH,4a01c3afbc224,1541680104,6,filter selection,Hotel,JP,"Yokohama, Japan",desktop,Hotel|Resort,NaN,NaN
22,02AOAVF9PVYH,4a01c3afbc224,1541680104,7,filter selection,Resort,JP,"Yokohama, Japan",desktop,Hotel|Resort,NaN,NaN
23,02AOAVF9PVYH,4a01c3afbc224,1541680261,8,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
24,02AOAVF9PVYH,4a01c3afbc224,1541680261,9,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
25,02AOAVF9PVYH,4a01c3afbc224,1541680271,10,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
26,02AOAVF9PVYH,4a01c3afbc224,1541680271,11,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
27,02AOAVF9PVYH,4a01c3afbc224,1541680271,12,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
28,02AOAVF9PVYH,4a01c3afbc224,1541680271,13,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
29,02AOAVF9PVYH,4a01c3afbc224,1541680271,14,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
30,02AOAVF9PVYH,4a01c3afbc224,1541680271,15,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
31,02AOAVF9PVYH,4a01c3afbc224,1541680271,16,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
32,02AOAVF9PVYH,4a01c3afbc224,1541680271,17,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
33,02AOAVF9PVYH,4a01c3afbc224,1541680271,18,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
34,02AOAVF9PVYH,4a01c3afbc224,1541680281,19,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
35,02AOAVF9PVYH,4a01c3afbc224,1541680281,20,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
36,02AOAVF9PVYH,4a01c3afbc224,1541680281,21,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
37,02AOAVF9PVYH,4a01c3afbc224,1541680281,22,interaction item image,749491,JP,"Yokohama, Japan",desktop,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3782291,ZXGCLNDBW84E,e73c90b6f448e,1541696386,440,interaction item image,1953137,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782292,ZXGCLNDBW84E,e73c90b6f448e,1541696396,441,interaction item image,1953137,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782293,ZXGCLNDBW84E,e73c90b6f448e,1541696396,442,interaction item image,1953137,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782294,ZXGCLNDBW84E,e73c90b6f448e,1541696396,443,interaction item info,1953137,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782295,ZXGCLNDBW84E,e73c90b6f448e,1541696591,444,interaction item image,1668443,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782296,ZXGCLNDBW84E,e73c90b6f448e,1541696824,445,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782297,ZXGCLNDBW84E,e73c90b6f448e,1541696824,446,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782298,ZXGCLNDBW84E,e73c90b6f448e,1541696836,447,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782299,ZXGCLNDBW84E,e73c90b6f448e,1541696836,448,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782300,ZXGCLNDBW84E,e73c90b6f448e,1541696836,449,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782301,ZXGCLNDBW84E,e73c90b6f448e,1541696836,450,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782302,ZXGCLNDBW84E,e73c90b6f448e,1541696836,451,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782303,ZXGCLNDBW84E,e73c90b6f448e,1541696836,452,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782304,ZXGCLNDBW84E,e73c90b6f448e,1541696836,453,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782305,ZXGCLNDBW84E,e73c90b6f448e,1541696846,454,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782306,ZXGCLNDBW84E,e73c90b6f448e,1541696846,455,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782307,ZXGCLNDBW84E,e73c90b6f448e,1541696846,456,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782308,ZXGCLNDBW84E,e73c90b6f448e,1541696846,457,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782309,ZXGCLNDBW84E,e73c90b6f448e,1541696846,458,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782310,ZXGCLNDBW84E,e73c90b6f448e,1541696846,459,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782311,ZXGCLNDBW84E,e73c90b6f448e,1541696846,460,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782312,ZXGCLNDBW84E,e73c90b6f448e,1541696846,461,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782313,ZXGCLNDBW84E,e73c90b6f448e,1541696846,462,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782314,ZXGCLNDBW84E,e73c90b6f448e,1541696846,463,interaction item image,1668425,BR,"Porto Seguro, Brazil",desktop,NaN,NaN,NaN
3782317,ZXGCLNDBW84E,e73c90b6f448e,1541699269,466,clickout item,NaN,BR,"Porto Seguro, Brazil",desktop,NaN,916029|1650015|326846|503361|1326068|477936|38...,60|81|140|171|49|42|38|60|57|74|191|71|55|45|5...
3782328,ZZ39YE45SZIE,f5db4092ec9fc,1541551871,1,interaction item info,5779140,HK,"Taitung City, Taiwan",mobile,NaN,NaN,NaN
3782329,ZZ39YE45SZIE,f5db4092ec9fc,1541551888,2,interaction item image,2849116,HK,"Taitung City, Taiwan",mobile,NaN,NaN,NaN
3782330,ZZ39YE45SZIE,f5db4092ec9fc,1541551888,3,interaction item image,2849116,HK,"Taitung City, Taiwan",mobile,NaN,NaN,NaN
3782332,ZZ39YE45SZIE,f5db4092ec9fc,1541551899,5,interaction item image,2849116,HK,"Taitung City, Taiwan",mobile,NaN,NaN,NaN
3782333,ZZ39YE45SZIE,f5db4092ec9fc,1541551945,6,clickout item,NaN,HK,"Taitung City, Taiwan",mobile,NaN,9925140|2625125|5779140|7365168|5849342|198775...,219|215|183|215|590|70|131|111|64|65|127|94|64...

In [28]:
df_many_no_clickout['reference_int'] = df_many_no_clickout.reference.apply(only_number)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [29]:
df_many_with_clickout['reference_int'] = df_many_with_clickout.reference.apply(only_number)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [0]:
df_ref_count_no_clickout = reference_count(df_many_no_clickout)

In [37]:
df_ref_count_no_clickout

           session_id  reference_int  ref_count
0       000177b850519        17011.0          1
1       000177b850519        17266.0          1
2       00017b3b2c136      6698142.0          9
3       000246890bfc6        98934.0          8
4       000246890bfc6        98938.0          2
5       000246890bfc6        98916.0          1
6       000356259e25a        43174.0          1
7       0003ce539baa5        70909.0          5
8       0003ce539baa5       959569.0          3
9       0003ce539baa5        76808.0          2
10      0003ce539baa5        75896.0          1
11      0008cd59f6797       961609.0          8
12      0008cd59f6797      6007216.0          2
13      000b7d3346b45       111076.0         28
14      000b7d3346b45       819356.0         12
15      000bb397ca596      3372506.0         15
16      000bb397ca596      4204380.0         11
17      000bb397ca596       868846.0          4
18      000bb397ca596      3453502.0          3
19      000bb397ca596        36518.0          2
20      000bb397ca596       486356.0          2
21      000bb397ca596         9169.0          1
22      000bb397ca596        36491.0          1
23      000bb397ca596        97056.0          1
24      000bb397ca596      2512326.0          1
25      000bb397ca596      2808546.0          1
26      000bf92665196      2633415.0          8
27      000bf92665196        18407.0          1
28      000c98c2ace32        53709.0          1
29      000cb3e20625d      8734912.0          3
...               ...            ...        ...
172508  fff1f763f68f2      1433222.0          5
172509  fff2489d87009        91802.0          4
172510  fff30aa392b71        58206.0          3
172511  fff30aa392b71      4427348.0          1
172512  fff321b155db4      7195708.0         31
172513  fff321b155db4         8445.0         18
172514  fff321b155db4         8454.0         10
172515  fff32ff7546ae       104802.0         38
172516  fff32ff7546ae       104888.0          6
172517  fff32ff7546ae       104889.0          1
172518  fff5038fb59f9        20843.0          1
172519  fff59368e2c39      2718170.0         17
172520  fff5d36738d37      9822446.0          1
172521  fff777604f3a7      1007613.0          9
172522  fff777604f3a7      7128186.0          5
172523  fff777604f3a7      2248622.0          2
172524  fff8620423860       159224.0          1
172525  fffa850e80f11      5965756.0          2
172526  fffb3cdffa24c      1320200.0          1
172527  fffbe4e4a6f5d      1121606.0          2
172528  fffbe4e4a6f5d      1320551.0          1
172529  fffbe4e4a6f5d      3065810.0          1
172530  fffbe4e4a6f5d      7117832.0          1
172531  fffe54dd22bff      3247218.0          2
172532  ffff07dfc9efa      3861898.0          2
172533  ffff0ad1c618d       147189.0          3
172534  ffff51afaec25       808546.0         33
172535  ffff51afaec25      1293592.0          1
172536  ffff51afaec25      2027033.0          1
172537  mc56p18be6c2g     10527680.0          1

[172538 rows x 3 columns]

In [0]:
df_ref_count_with_clickout = reference_count(df_many_with_clickout)

In [0]:
# mapping two dataframes 
df_new = df_ref_count_no_clickout.merge(df_ref_count_with_clickout.drop('ref_count', axis = 1).rename(columns = {"reference_int" : "clickout"}), left_on = ['session_id', 'reference_int'], right_on = ['session_id', 'clickout'], how = 'left')

In [0]:
df_ref_count =  df_new.loc[df_new.reference_int != df_new.clickout]

In [0]:
df_ref_count = df_ref_count.drop("clickout", axis = 1)

In [0]:
df_target = f.get_submission_target(df_many)

In [0]:
df_expl = f.explode(df_target, 'impressions')

In [0]:
df_out = ref_recommendation(df_expl, df_ref_count)

In [0]:
df_out.to_csv(path + "many.csv")

In [0]:
mono = pd.read_csv(path + 'mono.csv', )
many = pd.read_csv(path + 'many.csv')

In [0]:
mono = mono.drop('Unnamed: 0', axis = 1)
many = many.drop('Unnamed: 0', axis = 1)

In [66]:
many.session_id.nunique() + mono.session_id.nunique()

253573

In [0]:
submission = pd.concat([mono,many], ignore_index = True).sort_values(by = ['user_id']).reset_index(drop = True)

In [0]:
submission.to_csv(path + '190506.csv', index = False)